services:
    backend:
        container_name: go-backend
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "${APP_PORT}:${APP_PORT}"
        env_file:
            - .env
        depends_on:
            - db
        networks:
            - app-network

    db:
        container_name: postgres-db
        image: postgres:16
        restart: always
        env_file:
            - .env
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - "${DB_PORT}:${DB_PORT}"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
